# Generated by Django 4.0 on 2021-12-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
